<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FluentValidation" Version="11.9.1" />
    <PackageVersion Include="LogicMonitor.Api" Version="3.*" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="7.*" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.*" />
    <PackageVersion Include="Serilog" Version="2.*" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="5.*" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="3.*" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="4.*" />
    <PackageVersion Include="System.Text.Json" Version="8.*" />
  </ItemGroup>
</Project>